### ISSUE TITLE
Node Modules Not working

### ISSUE THREAD

**Issue by jackchi** [rossettistone/opentok-classroom#4]
=> Meteor server running on: http://localhost:3000/
TypeError: undefined is not a function
    at app/packages/node-modules/server.js:2:12
    at /Users/guest/Desktop/hack-meat/opentok-classroom/.meteor/local/build/server/server.js:298:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/guest/.meteor/tools/cc18dfef9e/lib/node_modules/underscore/underscore.js:78:11)
    at run (/Users/guest/Desktop/hack-meat/opentok-classroom/.meteor/local/build/server/server.js:239:7)
=> Exited with code: 1

**Comment by aykutyaman** [comment]
same issue for me
